version: '3.7'

services:
  urbackup:
    build: .
    container_name: "urbackup-client"
    restart: 'always'
    ports: 
     - 35621:35621
     - 35622:35622
     - 35623:35623
    volumes:
     - ../app:/usr/backup



